
from core.capabilities.base.capability import Capability


class AutoSkillCapability(Capability):

    name = "auto_skill"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "auto_skill" in text



    def handle(self,text):

        return {
            "capability":"auto_skill",
            "status":"active",
            "version":self.version
        }



capability = AutoSkillCapability()
