
from core.capabilities.base.capability import Capability


class SelfEvolutionCapability(Capability):

    name = "self_evolution"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "self_evolution" in text



    def handle(self,text):

        return {
            "capability":"self_evolution",
            "status":"active",
            "version":self.version
        }



capability = SelfEvolutionCapability()
