
from core.capabilities.base.capability import Capability


class TestSkillCapability(Capability):

    name = "test_skill"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "test_skill" in text



    def handle(self,text):

        return {
            "capability":"test_skill",
            "status":"active",
            "version":self.version
        }



capability = TestSkillCapability()
