
from core.capabilities.base.capability import Capability


class ToolsCapability(Capability):

    name = "tools"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "tools" in text



    def handle(self,text):

        return {
            "capability":"tools",
            "status":"active",
            "version":self.version
        }



capability = ToolsCapability()
