
from core.capabilities.base.capability import Capability


class VoiceInputCapability(Capability):

    name = "voice_input"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "voice_input" in text



    def handle(self,text):

        return {
            "capability":"voice_input",
            "status":"active",
            "version":self.version
        }



capability = VoiceInputCapability()
