
from core.capabilities.base.capability import Capability


class WebCapability(Capability):

    name = "web"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "web" in text



    def handle(self,text):

        return {
            "capability":"web",
            "status":"active",
            "version":self.version
        }



capability = WebCapability()
