from datetime import datetime
from core.projects.intent_analyzer import intent_analyzer
from core.projects.engine.test_engine import test_engine
from core.projects.engine.debug_engine import debug_engine
import os
import json
from core.templates.template_engine import template_engine
from core.templates.brain.adaptive_template_brain import adaptive_template_brain
from core.templates.brain.evolution_engine import template_evolution
from core.templates.template_brain import template_brain
from core.templates.smart_selector import smart_selector
from core.templates.template_selector import template_selector
from core.templates.adaptive_template_manager import adaptive_template_manager
from core.projects.engine.code_engine import code_engine
from core.projects.generator.file_generator import file_generator
from core.projects.engine.code_engine import code_engine
from core.projects.generator.file_generator import file_generator
from core.projects.engine.test_engine import test_engine



class FullBuilderEngine:


    def __init__(self):

        self.projects = []



    def analyze(self, request):

        return {
            "request": request,
            "type": "application",
            "status": "analyzed"
        }



    def select_stack(self, project_type):

        return {
            "language": "python",
            "database": "sqlite",
            "interface": "ui",
            "status": "selected"
        }



    def create_project(self, name):

        path = f"projects/{name}"

        os.makedirs(
            path,
            exist_ok=True
        )

        files = [
            "main.py",
            "database.py",
            "config.py",
            "requirements.txt",
            "test.py",
            "README.md"
        ]


        for file in files:

            with open(
                f"{path}/{file}",
                "w",
                encoding="utf-8"
            ) as f:

                f.write(
                    "# Generated by Sepehr Builder\n"
                )


        return {
            "files": files,
            "status": "created"
        }



    def generate_code(self, name, request):


        intent = intent_analyzer.analyze(request)


        template = template_brain.generate(
            request
        )


        if isinstance(template, dict):

            templates = template

        else:

            templates = template_engine.load(
                template
            )


        return code_engine.generate(
            name,
            templates
        )


    def install_dependencies(self):

        return {
            "dependencies":[
                "planned"
            ],
            "status":"ready"
        }



    def test(self, name):

        return test_engine.run(name)



    def debug(self, name):

        result = self.test(name)

        if result.get("status") == "failed":

            return debug_engine.analyze(
                result.get("output")
            )

        return {
            "project":name,
            "errors":0,
            "status":"clean"
        }



    def deliver(self, name):

        return {
            "project":name,
            "delivery":"completed",
            "status":"ready"
        }



    def build(self, request):

        intent = intent_analyzer.analyze(request)


        name = request.replace(
            " ",
            "_"
        )


        pipeline = []


        pipeline.append(intent)


        analysis = self.analyze(request)
        pipeline.append(analysis)


        pipeline.append(
            self.select_stack(
                analysis["type"]
            )
        )


        pipeline.append(
            self.create_project(name)
        )


        pipeline.append(
            self.generate_code(name, request)
        )


        pipeline.append(
            self.install_dependencies()
        )


        pipeline.append(
            self.test(name)
        )


        pipeline.append(
            self.debug(name)
        )


        pipeline.append(
            self.deliver(name)
        )


        self.projects.append(name)


        return {
            "project":name,
            "pipeline":pipeline,
            "status":"completed"
        }



builder = FullBuilderEngine()
