from datetime import datetime
import os
import json
from core.projects.engine.code_engine import code_engine
from core.projects.engine.test_engine import test_engine



class FullBuilderEngine:


    def __init__(self):

        self.projects = []



    def analyze(self, request):

        return {
            "request": request,
            "type": "application",
            "status": "analyzed"
        }



    def select_stack(self, project_type):

        return {
            "language": "python",
            "database": "sqlite",
            "interface": "ui",
            "status": "selected"
        }



    def create_project(self, name):

        path = f"projects/{name}"

        os.makedirs(
            path,
            exist_ok=True
        )

        files = [
            "main.py",
            "database.py",
            "config.py",
            "requirements.txt",
            "test.py",
            "README.md"
        ]


        for file in files:

            with open(
                f"{path}/{file}",
                "w",
                encoding="utf-8"
            ) as f:

                f.write(
                    "# Generated by Sepehr Builder\n"
                )


        return {
            "files": files,
            "status": "created"
        }



    def generate_code(self, name):

        files = {
            "main.py": "print('Sepehr generated app running')\n",
            "database.py": "import sqlite3\n",
            "test.py": "print('Generated test')\n"
        }

        result = []

        for filename, content in files.items():

            result.append(
                code_engine.create_file(
                    name,
                    filename,
                    content
                )
            )

        return {
            "files": result,
            "status": "code_generated"
        }


    def install_dependencies(self):

        return {
            "dependencies":[
                "planned"
            ],
            "status":"ready"
        }



    def test(self, name):

        return {
            "project":name,
            "tests":"executed",
            "status":"passed"
        }



    def debug(self, name):

        return {
            "project":name,
            "errors":0,
            "status":"clean"
        }



    def deliver(self, name):

        return {
            "project":name,
            "delivery":"completed",
            "status":"ready"
        }



    def build(self, request):

        name = request.replace(
            " ",
            "_"
        )


        pipeline = []


        analysis = self.analyze(request)
        pipeline.append(analysis)


        pipeline.append(
            self.select_stack(
                analysis["type"]
            )
        )


        pipeline.append(
            self.create_project(name)
        )


        pipeline.append(
            self.generate_code(name)
        )


        pipeline.append(
            self.install_dependencies()
        )


        pipeline.append(
            self.test(name)
        )


        pipeline.append(
            self.debug(name)
        )


        pipeline.append(
            self.deliver(name)
        )


        self.projects.append(name)


        return {
            "project":name,
            "pipeline":pipeline,
            "status":"completed"
        }



builder = FullBuilderEngine()
