import os
import json


# 1 Template Registry
os.makedirs("core/templates/registry", exist_ok=True)

with open("core/templates/registry/templates.json","w",encoding="utf-8") as f:
    json.dump({
        "calculator":["operations","testing"],
        "ecommerce":["products","users","cart","inventory"],
        "car_marketplace":["cars","users","database"],
        "hospital":["patients","doctors","database"],
        "restaurant":["menu","orders","users"],
        "farm_management":["plants","inventory","database"],
        "mobile_shop":["products","sales","inventory"]
    },f,indent=4,ensure_ascii=False)


# 2 Validator
with open("core/templates/template_validator.py","w",encoding="utf-8") as f:
    f.write("""
import os

class TemplateValidator:

    def validate(self,path):
        required=[
            "main.py.template",
            "database.py.template",
            "test.py.template"
        ]

        ok=all(
            os.path.exists(
                os.path.join(path,x)
            )
            for x in required
        )

        return {
            "valid":ok,
            "path":path
        }


template_validator=TemplateValidator()
""")


# 3 Smart selector
with open("core/templates/smart_selector.py","w",encoding="utf-8") as f:
    f.write("""
import os
import json

class SmartTemplateSelector:

    def __init__(self):
        with open(
        "core/templates/registry/templates.json",
        encoding="utf-8"
        ) as f:
            self.registry=json.load(f)


    def select(self,features):

        for name,data in self.registry.items():

            if any(x in features for x in data):
                return name

        return "general"


smart_selector=SmartTemplateSelector()
""")


# 4 fallback template
os.makedirs(
"core/templates/generated/general",
exist_ok=True
)

for file,content in {
"main.py.template":
'print("Generated by Sepehr General Template")',

"database.py.template":
'class Database:\\n    pass',

"test.py.template":
'print("template test passed")'

}.items():

    with open(
    "core/templates/generated/general/"+file,
    "w",
    encoding="utf-8"
    ) as f:
        f.write(content)



# 5 connect builder marker
path="core/builder/full_builder_engine.py"

if os.path.exists(path):

    with open(path,encoding="utf-8") as f:
        data=f.read()

    if "smart_selector" not in data:

        data=data.replace(
        "from core.templates.template_engine import template_engine",
        """from core.templates.template_engine import template_engine
from core.templates.smart_selector import smart_selector"""
        )

    with open(path,"w",encoding="utf-8") as f:
        f.write(data)


# 6 tests
print("TEMPLATE SYSTEM FINAL UPGRADE COMPLETE")

