
from core.capabilities.base.capability import Capability


class GreenhouseManagerAiCapability(Capability):

    name = "greenhouse_manager_ai"

    purpose = "autogenerated capability"

    aliases = [
        "greenhouse_manager_ai",
        "greenhouse manager"
    ]


    def can_handle(self, text):

        text = text.lower()

        return any(
            alias.lower() in text
            for alias in self.aliases
        )


    def handle(self, text):

        return {
            "capability": "greenhouse_manager_ai",
            "status": "active",
            "version": self.version
        }


capability = GreenhouseManagerAiCapability()
