
from core.capabilities.base.capability import Capability


class InventoryAiCapability(Capability):

    name = "inventory_ai"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "inventory_ai" in text



    def handle(self,text):

        return {
            "capability":"inventory_ai",
            "status":"active",
            "version":self.version
        }



capability = InventoryAiCapability()
