
from core.capabilities.base.capability import Capability


class TestAiCapability(Capability):

    name = "test_ai"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "test_ai" in text



    def handle(self,text):

        return {
            "capability":"test_ai",
            "status":"active",
            "version":self.version
        }



capability = TestAiCapability()
