
from core.capabilities.base.capability import Capability


class TestAutoGeneratedAiCapability(Capability):

    name = "test_auto_generated_ai"

    purpose = "autogenerated capability"

    aliases = [
        "test_auto_generated_ai",
        "test auto generated"
    ]

    keywords = [
        "test auto generated",
        "test_auto_generated_ai".replace("_ai","")
    ]


    def can_handle(self, text):

        text = text.lower()

        return any(
            alias.lower() in text
            for alias in self.aliases
        )


    def handle(self, text):

        return {
            "capability": "test_auto_generated_ai",
            "status": "active",
            "version": self.version
        }


capability = TestAutoGeneratedAiCapability()
