
from core.capabilities.base.capability import Capability


class VoiceOutputCapability(Capability):

    name = "voice_output"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "voice_output" in text



    def handle(self,text):

        return {
            "capability":"voice_output",
            "status":"active",
            "version":self.version
        }



capability = VoiceOutputCapability()
