
from core.capabilities.base.capability import Capability


class سلامAiCapability(Capability):

    name = "سلام_ai"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "سلام_ai" in text



    def handle(self,text):

        return {
            "capability":"سلام_ai",
            "status":"active",
            "version":self.version
        }



capability = سلامAiCapability()
