
from core.capabilities.base.capability import Capability


class مدیریتمرغداریAiCapability(Capability):

    name = "مدیریت_مرغداری_ai"

    purpose = "autogenerated capability"

    aliases = [
        "مدیریت_مرغداری_ai",
        "مدیریت مرغداری"
    ]


    def can_handle(self, text):

        text = text.lower()

        return any(
            alias.lower() in text
            for alias in self.aliases
        )


    def handle(self, text):

        return {
            "capability": "مدیریت_مرغداری_ai",
            "status": "active",
            "version": self.version
        }


capability = مدیریتمرغداریAiCapability()
