
from core.capabilities.base.capability import Capability


class مدیریتگلخانهAiCapability(Capability):

    name = "مدیریت_گلخانه_ai"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "مدیریت_گلخانه_ai" in text



    def handle(self,text):

        return {
            "capability":"مدیریت_گلخانه_ai",
            "status":"active",
            "version":self.version
        }



capability = مدیریتگلخانهAiCapability()
