
from core.capabilities.base.capability import Capability


class منAiCapability(Capability):

    name = "من_ai"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "من_ai" in text



    def handle(self,text):

        return {
            "capability":"من_ai",
            "status":"active",
            "version":self.version
        }



capability = منAiCapability()
