
from core.capabilities.base.capability import Capability


class یکAiCapability(Capability):

    name = "یک_ai"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "یک_ai" in text



    def handle(self,text):

        return {
            "capability":"یک_ai",
            "status":"active",
            "version":self.version
        }



capability = یکAiCapability()
