

import os
import json


class TemplateBrain:


    def __init__(self):

        self.memory="data/template_memory.json"

        os.makedirs("data",exist_ok=True)

        if not os.path.exists(self.memory):

            json.dump({},open(self.memory,"w"))



    def understand(self,request):

        words=request.split()

        project="general"


        rules={

        "shop":["فروشگاه","فروش","خرید"],
        "medical":["بیمارستان","پزشک","سلامت"],
        "media":["عکس","فیلم","ادیت"],
        "repair":["تعمیر","تعمیرات"],
        "farm":["مزرعه","کشاورزی"],
        "vehicle":["ماشین","خودرو","قطعات"]

        }


        for k,v in rules.items():

            for x in v:

                if x in request:
                    project=k


        return project



    def design_features(self,ptype):


        base={

        "shop":
        [
        "users",
        "products",
        "cart",
        "orders",
        "database"
        ],


        "medical":
        [
        "patients",
        "doctors",
        "appointments",
        "database"
        ],


        "media":
        [
        "files",
        "editor",
        "storage"
        ],


        "repair":
        [
        "customers",
        "vehicles",
        "services",
        "invoice",
        "database"
        ],


        "farm":
        [
        "plants",
        "workers",
        "records",
        "database"
        ],


        "vehicle":
        [
        "products",
        "inventory",
        "customers",
        "database"
        ],


        "general":
        [
        "database",
        "interface"
        ]

        }


        return base.get(ptype,base["general"])



    def create_template(self,ptype,features):


        path=f"core/templates/generated/{ptype}"


        os.makedirs(path,exist_ok=True)


        files=["main.py.template",
        "database.py.template",
        "models.py.template",
        "test.py.template"]


        for f in files:


            open(
            f"{path}/{f}",
            "w",
            encoding="utf8"
            ).write(

f"""
# Generated by Sepehr AI

# Project:
# {ptype}

# Features:
# {features}

"""
            )


        return path




    def generate(self,request):


        ptype=self.understand(request)

        features=self.design_features(ptype)


        path=self.create_template(
            ptype,
            features
        )


        return {

        "type":ptype,
        "features":features,
        "template":path

        }



template_brain=TemplateBrain()

