import os


def run_code_engine(text):
    """
    ساخت پروژه واقعی از متن کاربر
    """

    print("💻 Code Engine فعال شد")

    project_name = extract_project_name(text)

    base_path = f"./generated/{project_name}"

    os.makedirs(base_path, exist_ok=True)

    create_main_file(base_path, project_name)
    create_readme(base_path, project_name, text)

    return f"""
🚀 پروژه ساخته شد:

📁 مسیر: {base_path}

📌 پروژه: {project_name}

⚙ آماده اجرا
"""


def extract_project_name(text):
    """
    استخراج اسم پروژه به شکل هوشمند
    """

    stop_words = [
        "بساز", "کن", "بده", "برام", "یه", "یک", "اپ", "برنامه"
    ]

    words = text.split()

    filtered = []

    for w in words:
        if w not in stop_words and len(w) > 2:
            filtered.append(w)

    if not filtered:
        return "my_app"

    return "_".join(filtered[-2:])


def create_main_file(path, name):

    code = f"""# {name}

print("Hello from {name} 🚀")
"""

    with open(f"{path}/main.py", "w", encoding="utf-8") as f:
        f.write(code)


def create_readme(path, name, text):

    content = f"""# {name}

Generated by Sepehr AI

Request:
{text}

Status: Ready
"""

    with open(f"{path}/README.md", "w", encoding="utf-8") as f:
        f.write(content)
