import os


BASE = "projects"


def create_project_files(project_name):

    folder = project_name.replace(" ", "_")

    path = os.path.join(BASE, folder)

    os.makedirs(path, exist_ok=True)


    files = {

        "main.py":
'''from calculator import add, subtract, multiply, divide


print("Calculator App")

print(add(2,3))
''',


        "calculator.py":
'''def add(a,b):
    return a+b


def subtract(a,b):
    return a-b


def multiply(a,b):
    return a*b


def divide(a,b):

    if b == 0:
        return None

    return a/b
''',


        "README.md":
'''# Calculator App

Generated by Sepehr2 AI
'''
    }


    for name, content in files.items():

        file_path = os.path.join(path, name)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)


    return path
