from core.template_loader import TemplateLoader


class TemplateManager:

    def __init__(self):
        self.loader = TemplateLoader()

    def get_template(self, project_type, filename):

        code = self.loader.load(
            project_type,
            filename
        )

        if code.strip():
            return code

        return self.generate_default(filename)

    def generate_default(self, filename):

        if filename.endswith(".py"):
            return f'''"""
{filename}
Generated by Sepehr2
"""

'''

        if filename.endswith(".txt"):
            return ""

        return ""
