from datetime import datetime
import os
import json


class UniversalBuilderAgent:


    def __init__(self):

        self.projects = []



    def analyze_request(self, request):

        return {
            "request": request,
            "requirements": [
                "architecture",
                "files",
                "code",
                "test"
            ],
            "status":"analyzed"
        }



    def create_structure(self, name):

        path = f"projects/{name}"

        os.makedirs(
            path,
            exist_ok=True
        )


        files = [
            "main.py",
            "database.py",
            "README.md",
            "test.py"
        ]


        for file in files:

            open(
                f"{path}/{file}",
                "w",
                encoding="utf-8"
            ).write(
                "# Generated by Sepehr\n"
            )


        return {
            "project":name,
            "files":files,
            "status":"created"
        }



    def generate_code(self, name):

        return {
            "project":name,
            "code_engine":"active",
            "status":"generated"
        }



    def test_project(self, name):

        return {
            "project":name,
            "tests":"completed",
            "status":"passed"
        }



    def build(self, request):

        name = request.replace(
            " ",
            "_"
        )


        result = []


        result.append(
            self.analyze_request(
                request
            )
        )


        result.append(
            self.create_structure(
                name
            )
        )


        result.append(
            self.generate_code(
                name
            )
        )


        result.append(
            self.test_project(
                name
            )
        )


        self.projects.append(name)


        return {
            "project":name,
            "pipeline":result,
            "status":"delivered"
        }



builder = UniversalBuilderAgent()


print(
    builder.build(
        "car marketplace app"
    )
)


print(
    {
        "projects":builder.projects,
        "status":"universal_builder_active",
        "time":str(datetime.now())
    }
)

