import os


class FileGenerator:


    name = "file_generator"


    def generate(self, project, features):

        files = []


        mapping = {

            "products": "products.py",

            "users": "users.py",

            "cart": "cart.py",

            "inventory": "inventory.py",

            "database": "database.py",

            "customers": "customers.py",

            "orders": "orders.py",

            "operations": "calculator.py",

            "testing": "test.py"

        }


        os.makedirs(
            f"projects/{project}",
            exist_ok=True
        )


        for feature in features:

            if feature in mapping:

                filename = mapping[feature]

                path = f"projects/{project}/{filename}"


                with open(
                    path,
                    "w",
                    encoding="utf-8"
                ) as f:

                    f.write(
f"""# Generated by Sepehr
# Feature: {feature}


class {feature.capitalize()}:

    def __init__(self):
        self.name = "{feature}"


"""
                    )


                files.append(path)


        return {

            "files": files,

            "status": "files_generated"

        }



file_generator = FileGenerator()
