class TemplateEngine:


    name = "template_engine"


    def __init__(self):

        self.templates = {

            "calculator": {

                "main.py": """
def add(a,b):
    return a+b


def subtract(a,b):
    return a-b


def multiply(a,b):
    return a*b


def divide(a,b):
    return a/b


if __name__ == "__main__":
    print(add(5,3))
"""
            },


            "basic": {

                "main.py": """
def main():

    print("Generated by Sepehr Builder")


if __name__ == "__main__":
    main()
"""
            }

        }



    def select(self, request):

        text = request.lower()


        if "ماشین حساب" in text or "calculator" in text:

            return self.templates["calculator"]


        return self.templates["basic"]



template_engine = TemplateEngine()
