import os

from core.learning.capability_tester import capability_tester


class CapabilityCreator:


    def create(self, name):


        filename = f"core/capabilities/{name}.py"


        if os.path.exists(filename):

            return {
                "status":"exists",
                "file":filename
            }


        class_name = (
            name.title()
            .replace("_","")
            + "Capability"
        )


        template = f'''
from core.capabilities.base.capability import Capability


class {class_name}(Capability):

    name = "{name}"

    purpose = "autogenerated capability"


    def can_handle(self,text):

        return "{name}" in text



    def handle(self,text):

        return {{
            "capability":"{name}",
            "status":"active",
            "version":self.version
        }}



capability = {class_name}()
'''


        with open(
            filename,
            "w",
            encoding="utf-8"
        ) as f:

            f.write(template)


        test = capability_tester.test(
            name
        )


        return {

            "status":"created",

            "file":filename,

            "test":test

        }



capability_creator = CapabilityCreator()
