from core.actions.action import Action

from core.projects.engine.project_manager import project_manager
from core.projects.engine.code_engine import code_engine
from core.projects.engine.test_engine import test_engine
from core.projects.engine.debug_engine import debug_engine


def analyze(context):

    return {
        "step":"analyze",
        "task":context
    }



def reason(context):

    return {
        "step":"reason",
        "decision":"project architecture selected"
    }



def plan(context):

    return {
        "step":"plan",
        "steps":[
            "create structure",
            "write code",
            "test",
            "debug",
            "save"
        ]
    }



def generate(context):

    name = "generated_app"

    project = project_manager.create(name)


    file = code_engine.create_file(
        name,
        "main.py",
        "print('Generated by Sepehr2')"
    )


    return {
        "step":"generate",
        "project":project,
        "file":file,
        "name":name
    }



def test(context):

    return test_engine.run(
        "generated_app"
    )



def debug(context):

    return debug_engine.analyze(
        context
    )



def save(context):

    return {
        "step":"save",
        "status":"saved"
    }



def create_project_chain(manager):


    chain = manager.create(
        "project_build"
    )


    chain.add(Action("analyze", analyze))
    chain.add(Action("reason", reason))
    chain.add(Action("plan", plan))
    chain.add(Action("generate", generate))
    chain.add(Action("test", test))
    chain.add(Action("debug", debug))
    chain.add(Action("save", save))


    return chain
